dguest/pandamonium

pandamon
Dan! Small changes.
Setting default search string to `user.${USER}`. Also adding a `-t`/`--taskid` option to only output the taskID. Means things can be piped around without an awk in between. Now can just
```
pandamon "user.leejr*searchstring" -t | panda-kill-taskid 
```
without an `awk`ward `awk` in between.
=> Larry Improvements! -t option for taskID-only output. Set default search string.

pandamon
user option '-m' now prints the jedi task id and percent failed. the
former is more useful when browsing bigpanda/e-mails. the latter is
useful too for completeness.
=> add option to print more stuff

README.md, panda-kill-taskid, pandamon
Adding `-r` option to only display jobs with a specified range of taskIDs. Useful when you want to pipe only certain jobs to by retried (and not all of the failed jobs from your previous runs that you accidentally submitted with wrong parameters etc.)
=> New feature: filter jobs by taskid range

pandamon
Partially addresses #23 (might still be treated as Python 2 by default)
Use `try` and `except` blocks in the library imports to properly load the libraries that are divergent across Python 2 and Python 3. (Currently also showing the work of another PR)
=> feat: Make compatible with Python 2 and Python 3 runtimes

.github/workflows/publish-package.yml, README.md
Use the https://github.com/pypa/gh-action-pypi-publish to publish to TestPyPI every time a PR is merged.
**Suggested squash and merge commit message**
```
* Add publishing to TestPyPI on PR merge using the PyPA publishing GitHub Action
- c.f. https://github.com/pypa/gh-action-pypi-publish
* Direct users to use TestPyPI install until PyPI namespace is acquired
```
=> ci: Add distribution to TestPyPI

README.md
Add badges to README that add information on the current PyPI release version as well as the versions of Python that are supported for the PyPI release.
- [![PyPI version](https://badge.fury.io/py/pandamonium.svg)](https://badge.fury.io/py/pandamonium)
- [![Supported Python versions](https://img.shields.io/pypi/pyversions/pandamonium.svg)](https://pypi.org/project/pandamonium/)
**Suggested squash and merge commit message**
```
* Add badges for PyPI release version and supported Python versions to README
```
=> docs: Add PyPI info badges

README.md
Add installation from PyPI as the first listed installation method:
```
python -m pip install pandamonium
```
Additionally, still keep the TestPyPI instructions but note they are for dev releases and recommend that users use `--extra-index-url` as the installation method for installing from TestPyPI as this adds TestPyPI as [an additional package index to search](https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-extra-index-url) when installing `pandamonium` specifically. PyPI will still be the default package index `pip` will attempt to install from for all dependencies.
This didn't work when `pandamonium` on PyPI was not under our control, and so 
```
python -m pip install -i https://test.pypi.org/simple/ --pre pandamonium
```
was required after first installing …
=> docs: Add PyPI to install instructions

setup.py
@dguest has brought to my attention that [`bumpversion` is no longer maintained](https://github.com/peritus/bumpversion) (as of apparently November 2019). Given this we should probably take the project's advice
> 🎬 If you want to start using `bumpversion`, you're best advised to install one of the maintained forks, e.g. ➡ @ c4urself's [`bump2version`](https://github.com/c4urself/bump2version/#installation).
This PR migrates to using `bump2version` `v1.X` release series.
```
* Migrate from using bumpversion to bump2version in the develop extra
- bumpversion is no longer maintained and bump2version is the recommended fork
- Use bump2version v1.X series
```
=> chore: Migrate from bumpversion to bump2version

.github/workflows/lint.yml, .github/workflows/publish-package.yml
- Resolves #36 
- Resolves #26 
This PR uses publication type releases to publish to PyPI by running the publication workflow on `published` `release` events and then verifying that the PyPI upload step is running on one. This follows what I'll call the `corner` model (which I now think is how GitHub Actions assumed people would do things): 
This follows the example that is setup in [`corner`](https://github.com/dfm/corner.py) with running the workflow on [`published` `release` events](https://github.com/dfm/corner.py/blob/efd25380ee121c4d565ed9aff2f98e184cc9dcef/.github/workflows/tests.yml#L7-L8) and then only running the [publish to PyPI step on that conditions](https://github.com/dfm/corner.py/blob/efd25380ee121c4d565ed9aff2f98e184cc9dcef/.github/workflows/tests.yml#L82). To instigate …
=> ci: Publish releases to PyPI through GitHub releases

.github/workflows/publish-package.yml
My bad. :disappointed: 
**Squash and merge commit message:**
```
* Indent PyPI publishing YAML to align with rest of workflow
* Amends PR #41
```
=> fix: Correct YAML indentation

.github/workflows/publish-package.yml
(This is a port of https://github.com/scikit-hep/pylhe/pull/45)
With the old workflow if the publishing workflow was run after a new tag was created
```
$ bump2version <part>
$ git push origin master --tags
```
no release would get published to TestPyPI as the workflow that would get kicked off from the `push` event to `master` (and so NOT a `tag` event) would fail the "Verify untagged commits have dev versions" step
https://github.com/dguest/pandamonium/blob/3bcfd36525681fe56dc6dafee84a5f072533c833/.github/workflows/publish-package.yml#L37-L54
as it would
https://github.com/dguest/pandamonium/blob/3bcfd36525681fe56dc6dafee84a5f072533c833/.github/workflows/publish-package.yml#L38
but then also `"${wheel_name}" != *"dev"*` given that it comes from a tag. So nothing gets published. …
=> fix: Don't run publishing workflow on tags to avoid errors

src/pandamonium/pandamon.py
Resolves #49 
```
* Deprecate and remove 'reqid' in favor 'jeditaskid` given changes in PanDA's behavior
- Keep 'reqid' only for --more-info option
* Add note to --taskid help information to check the PanDA JEDI docs for more information on JEDITASKID
```
=> fix: Replace 'reqid' with 'jeditaskid' for taskid

.gitignore, .pre-commit-config.yaml, pyproject.toml, src/pandamonium/cli/cli.py, src/pandamonium/panda_kill_taskid.py, src/pandamonium/panda_resub_taskid.py, src/pandamonium/panda_shortname.py, src/pandamonium/pandamon.py
Resolves #7 
Address the points of Issue #7 and automatically make sure this issue does not come up again in the future by using [`isort`](https://pycqa.github.io/isort/) to sort imports and force them to the top of their Python files.
```
* Add isort to pre-commit hooks
- Add isort config options to pyproject.toml
* Apply isort to all Python files
- Alphabetically sort imports with one import per line
* Move all imports to the top of Python files
* Add VS Code workspace setting to gitignore
```
=> feat: Apply isort

.github/workflows/lint.yml, .github/workflows/publish-package.yml, pyproject.toml, setup.cfg
```
* Use Python 3.9 for packaging workflow
* Add Python 3.9 to PyPI metadata
* Remove --use-feature=2020-resolver from CI
- Use of this flag will become an error in future releases of pip 
```
=> ci: Use Python 3.9 for tests in CI

.github/workflows/lint.yml, README.md, setup.py
Resolves #53 
Add `isort` to the linting workflow in CI and add `isort` to the `lint` extra.
```
* Add isort to 'lint' extra
* Add isort to linting GHA workflow
* Add pre-commit.ci status badge to README
```
=> ci: Add isort to linting workflow

src/pandamonium/panda_kill_taskid.py, src/pandamonium/panda_resub_taskid.py
Resolves dguest/pandamonium#57 .  `pandatools` is renamed to `pandaclient`.
This will need a patch release to handle the API changes of the underlying tool.
```
* Adopt panda-client v1.4.82 `pandaclient` API
- c.f. https://github.com/PanDAWMS/panda-client/commit/eee3914e78347a427ae80a2588d181a6b8632dfb
```
=> fix: Update API to use panda-client v1.4.82 pandaclient API

.github/workflows/lint.yml, .github/workflows/publish-package.yml, .pre-commit-config.yaml
```
* Update pre-commit hooks and run order
- pre-commit runs hooks sequentially, so place isort before black
* Update pypa/gh-action-pypi-publish GitHub Action to v1.4.2
* Use updated build CLI API
* Add visual check of sdist contents
```
=> ci: Update pre-commit and CI to latest releases and APIs

MANIFEST.in
c.f. https://github.com/scikit-hep/pyhf/pull/1449
```
* Use `prune **` to remove all files from the sdist
- c.f. https://packaging.python.org/guides/using-manifest-in/#manifest-in-commands
- "Setuptools also has undocumented support for ** matching zero or more characters including forward slash, backslash, and colon."
* Manually include all "default" files for a sdist in MANIFEST.in
- c.f. https://packaging.python.org/guides/using-manifest-in/#how-files-are-included-in-an-sdist
```
=> chore: Revise MANIFEST.in strategy to properly use prune

.github/workflows/lint.yml, .github/workflows/publish-package.yml
```
* Update checkout and setup-python GitHub Actions to v3.
* Update gh-action-pypi-publish GitHub Action to v1.5.0.
- Add print_hash functionality.
* Update Python used for testing to 3.10.
* List contents of sdist and wheel.
```
=> ci: Update GitHub Action workflows

src/pandamonium/pandamon.py
This was being done wrong before: we'd loop over jobs and set the metadata to each one, rather than summing.
=> Fix how job metadata is summed

setup.cfg
As PR #66 patched a bug, it would probably be good to have a patch release, and before something goes up on PyPI it would be worthwhile to update the PyPI metadata.
=> docs: Add Python 3.10 to PyPI metadata

src/pandamonium/panda_kill_taskid.py, src/pandamonium/panda_resub_taskid.py
As discussed in https://github.com/dguest/pandamonium/issues/70#issuecomment-2163345574, for panda-client versions < 1.5.48, the check for proxy and extraction of username was done when you created a PBookCore object (from the initializer).  Now they default the username to None and to get it we have to call the init() function.
I tested this on top of master with command `panda-kill-taskid 39770381` (old `done` task that I had) and it worked (complained that you can't kill tasks in `done` state but that's beside the point).
=> Adding call to pbook additional init function
